#!/bin/bash

echo "Traitements pecl_http"
if [ ! -d ${OPENSHIFT_REPO_DIR}add_so ]; then
  mkdir ${OPENSHIFT_REPO_DIR}add_so
fi

if [ ! -f ${OPENSHIFT_REPO_DIR}add_so/http.so ]; then

  #
  # Compilation
  #
  
  PECL_HTTP="pecl_http-1.7.6"
  
  cd $OPENSHIFT_TMP_DIR
  # Telechargement
  wget https://pecl.php.net/get/${PECL_HTTP}.tgz
  tar xvf ${PECL_HTTP}.tgz
  
  cd ${PECL_HTTP}
  phpize
  ./configure
  # Compilation
  make
  
  # Copie du fichier
  cp ${OPENSHIFT_TMP_DIR}${PECL_HTTP}/modules/http.so ${OPENSHIFT_REPO_DIR}add_so/http.so
  
  # Nettoyage
  rm -R${OPENSHIFT_TMP_DIR}${PECL_HTTP}
  rm ${OPENSHIFT_TMP_DIR}${PECL_HTTP}.tgz
  
  
  # Activation de l'extension http
  echo "Creation fichier http.ini"
  echo "; Enable http extension module" > ${OPENSHIFT_PHP_DIR}configuration/etc/php.d/http.ini
  echo "extension=${OPENSHIFT_REPO_DIR}add_so/http.so" >> ${OPENSHIFT_PHP_DIR}configuration/etc/php.d/http.ini
fi

echo "Traitements Oracle Oci8"

if [ ! -f ${OPENSHIFT_REPO_DIR}add_so/oci8.so ]; then

  PECL_OCI8="oci8-1.4.10"
  
  cd $OPENSHIFT_TMP_DIR
  wget https://pecl.php.net/get/${PECL_OCI8}.tgz
  tar xvf ${PECL_OCI8}.tgz
  
  cd ${PECL_OCI8}
  phpize
  ./configure --with-oci8=instantclient,$OPENSHIFT_ORACLE_INSTANTCLIENT_DIR
  # Compilation
  make
  
  # Copie du fichier
  cp ${OPENSHIFT_TMP_DIR}${PECL_OCI8}/modules/oci8.so ${OPENSHIFT_REPO_DIR}add_so/oci8.so
  
  # Nettoyage
  rm -R ${OPENSHIFT_TMP_DIR}${PECL_OCI8}
  rm ${OPENSHIFT_TMP_DIR}${PECL_OCI8}.tgz
  
  # Activation de l'extension oci8
  echo "Creation fichier oci8.ini"
  echo "; Enable oci8 extension module" > ${OPENSHIFT_PHP_DIR}configuration/etc/php.d/oci8.ini
  echo "extension=${OPENSHIFT_REPO_DIR}add_so/oci8.so" >> ${OPENSHIFT_PHP_DIR}configuration/etc/php.d/oci8.ini
fi

# Bugg with Oracle version 12.2
# echo "Traitements Oracle PDO_Oci"

# if [ ! -f ${OPENSHIFT_REPO_DIR}add_so/pdo_oci.so ]; then

  # PECL_PDO_OCI="PDO_OCI-1.0"
  
  # cd $OPENSHIFT_TMP_DIR
  # wget https://pecl.php.net/get/${PECL_PDO_OCI}.tgz
  # tar xvf ${PECL_PDO_OCI}.tgz
  
  # cd ${PECL_PDO_OCI}
  # phpize
  # ./configure --with-pdo-oci=instantclient,$OPENSHIFT_ORACLE_INSTANTCLIENT_DIR
  # # Compilation
  # make
  
  # # Copie du fichier
  # cp ${OPENSHIFT_TMP_DIR}${PECL_PDO_OCI}/modules/pdo_oci.so ${OPENSHIFT_REPO_DIR}add_so/pdo_oci.so
  
  # # Nettoyage
  # rm -R ${OPENSHIFT_TMP_DIR}${PECL_PDO_OCI}
  # rm ${OPENSHIFT_TMP_DIR}${PECL_PDO_OCI}.tgz
  
  # # Activation de l'extension pdo_oci
  # echo "Creation fichier pdo_oci.ini"
  # echo "; Enable pdo_oci extension module" > ${OPENSHIFT_PHP_DIR}configuration/etc/php.d/pdo_oci.ini
  # echo "extension=${OPENSHIFT_REPO_DIR}add_so/pdo_oci.so" >> ${OPENSHIFT_PHP_DIR}configuration/etc/php.d/pdo_oci.ini
# fi
